@echo off

CALL LOG_ENTER bENV_GIT

CALL bENV_CAT
CALL bENV_TKN

if [%TMPL_URI%]==[] (
  CALL LOG_INVALID "TMPL_URI"
  CALL LOG_CMD "You must set it in .\env.cmd!"
  CALL LOG_CMD "Default value is https://github.com/itkunst"
  GOTO :EOF
)
CALL LOG_VAR TMPL_URI %TMPL_URI%

if [%TMPL_NAME%]==[] (
  CALL LOG_INVALID "TMPL_NAME"
  CALL LOG_CMD "You must set it in .\env.cmd!"
  GOTO :EOF
)
CALL LOG_VAR TMPL_NAME %TMPL_NAME%

IF  [%SYS%]==[] (
  CALL LOG_INVALID "SYS"
  CALL LOG_CMD "You must set it in .\env.cmd!"
  GOTO :EOF
)
CALL LOG_VAR SYS %SYS%

SET GLBL_GIT=%TMPL_URI%%SLASH%"zug_global.git"
CALL LOG_VAR GLBL_GIT %GLBL_GIT%

SET PROJ_GIT=%TMPL_URI%%SLASH%%TMPL_NAME%%DOT%%GIT%
CALL LOG_VAR PROJ_GIT %PROJ_GIT%

SET SYS_GIT=%UP%%SYS%%SPLIT%%SYSTEM%%DOT%%GIT%
CALL LOG_VAR SYS_GIT %SYS_GIT%

:EOF

CALL LOG_EXIT bENV_GIT
