@echo off

call :log_enter bENV_GIT

CALL bENV_CAT
CALL bENV_NAME
CALL bENV_TKN


IF  [%GLBL_NAME%]==[] (
  CALL LOG_INVALID "GLBL_NAME"
  GOTO :EOF
)
CALL LOG_VAR GLBL_NAME %GLBL_NAME%

IF  [%SYS%]==[] (
  CALL LOG_INVALID "SYS"
  CALL LOG_CMD "You must set it in .\env.cmd!"
  GOTO :EOF
)
CALL LOG_VAR SYS %SYS%

IF  [%SYS_GIT%]==[] (
  CALL LOG_INVALID "SYS_GIT"
  CALL LOG_CMD "You must set it in .\env.cmd!"
  GOTO :EOF
)
CALL LOG_VAR SYS_GIT %SYS_GIT%

if [%TMPL_NAME%]==[] (
  CALL LOG_INVALID "TMPL_NAME"
  CALL LOG_CMD "You must set it in .\env.cmd!"
  GOTO :EOF
)
CALL LOG_VAR TMPL_NAME %TMPL_NAME%

if [%TMPL_URI%]==[] (
  CALL LOG_INVALID "TMPL_URI"
  CALL LOG_CMD "You must set it in .\env.cmd!"
  CALL LOG_CMD "Default value is https://github.com/itkunst"
  GOTO :EOF
)
CALL LOG_VAR TMPL_URI %TMPL_URI%

SET "GLBL_GIT=%TMPL_URI%%SLASH%%GLOBAL_NAME%%DOT%%GIT%"
CALL LOG_VAR GLBL_GIT %GLBL_GIT%

SET "PROJ_GIT=%TMPL_URI%%SLASH%%TMPL_NAME%%DOT%%GIT%"
CALL LOG_VAR PROJ_GIT %PROJ_GIT%

CALL LOG_VAR SYS_GIT %SYS_GIT%

:EOF

call :log_exit bENV_GIT
