@echo off

CALL LOG_ENTER pCLONE_SYS


CALL bENV

if [%SYS_DIR%]==[] (
  CALL LOG_INVALID SYS_DIR
  goto :EOF
)
CALL LOG_VAR SYS_DIR %SYS_DIR%

if [%SYS_GIT%]==[] (
  CALL LOG_INVALID SYS_GIT
  goto :EOF
)
CALL LOG_VAR SYS_GIT %SYS_GIT%

SET INIT=0

IF NOT EXIST %SYS_DIR% (
  CALL pCLONE_REPO %SYS_GIT% %SYS_DIR%
  SET INIT=1
) else (
  CALL LOG_DUP %SYS_GIT%
)
CALL LOG_VAR ERRORLEVEL %ERRORLEVEL%

IF %ERRORLEVEL% NEQU 0 (
  CALL LOG_CLONE_ERR %SYS_GIT%
  CALL LOG_CMD "Does it exist in the repo?"
  goto :EOF
)

:EOF

CALL LOG_EXIT pCLONE_SYS

EXIT /B %ERRORLEVEL%