@echo off


CALL LOG_ENTER pCLONE_PROJ


CALL bENV

if [%DIR_PROJ%]==[] (
  CALL LOG_INVALID DIR_PROJ
  goto :EOF
)
CALL LOG_VAR DIR_PROJ %DIR_PROJ%

if [%PROJ_GIT%]==[] (
  CALL LOG_INVALID PROJ_GIT
  goto :EOF
)
CALL LOG_VAR PROJ_GIT %PROJ_GIT%

SET INIT=0

IF NOT EXIST %DIR_PROJ% (
  CALL pCLONE_REPO %PROJ_GIT% %DIR_PROJ%
  SET INIT=1
) else (
  call :log_dup %PROJ_GIT%
)
call LOG_VAR ERRORLEVEL %ERRORLEVEL%

IF %ERRORLEVEL% NEQU 0 (
  call :log_clone_err %PROJ_GIT%
  call LOG_CMD "Does it exist in the repo?"
  goto :EOF
)

:EOF

call LOG_EXIT pCLONE_PROJ

EXIT /B %ERRORLEVEL%